#!/usr/bin/env python3
"""Leakage-safe development analysis for a signed value-of-feedback router."""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

try:
    from analyze_counterfactual_feedback import binary_auc
except ModuleNotFoundError:
    from scripts.analyze_counterfactual_feedback import binary_auc


REPLAY_INTEGRITY_THRESHOLD = 1e-9
DEFAULT_QUERY_COST = 0.025
DEFAULT_BOOTSTRAP_REPETITIONS = 10_000
DEFAULT_BOOTSTRAP_SEED = 20260903
DEFAULT_BUDGETS = (0.10, 0.20, 0.30, 0.40, 0.50)
DEFAULT_BETAS = (0.0, 0.5, 1.0)

# All columns below are available before the extra query is issued. In
# particular, realized branch outcomes and feedback_endpoint_* are excluded.
PRE_QUERY_CORE_FEATURES = (
    "value_mean",
    "value_std",
    "value_range",
    "action_std_mean",
    "action_std_max",
    "action_first_step_l2_std",
    "action_pairwise_l2_mean",
    "future_proprio_std_mean",
    "future_image_pixel_std_mean",
    "future_wrist_pixel_std_mean",
    "latent_action_across_seed_std_mean",
    "latent_future_proprio_across_seed_std_mean",
    "latent_value_across_seed_std_mean",
    "latent_action_copy_std_mean_mean_over_samples",
    "latent_future_proprio_copy_std_mean_mean_over_samples",
    "latent_value_element_std_mean_mean_over_samples",
    "candidate_action_consensus_first_mean",
    "candidate_action_consensus_chunk_mean",
    "planning_predicted_proprio_error",
)

PRE_QUERY_STATE_ACTION_FEATURES = tuple(
    [f"pre_current_proprio_d{index}" for index in range(9)]
    + [f"open_candidate_action_first_d{index}" for index in range(7)]
    + [f"open_candidate_action_mean_d{index}" for index in range(7)]
    + [f"open_candidate_action_std_d{index}" for index in range(7)]
    + [f"open_candidate_predicted_future_proprio_d{index}" for index in range(9)]
)

# These are generated by the extra query before either old or new tail is
# executed. They can choose a tail, but they cannot save the query itself.
POST_QUERY_FEATURES = (
    "post_tail_l2_mean",
    "post_tail_l2_max",
    "post_tail_first_l2",
    "post_tail_xyz_l2_mean",
    "post_tail_rot_l2_mean",
    "post_tail_gripper_abs_mean",
    "post_tail_cosine_distance",
    "post_tail_sign_disagreement",
    "post_new_minus_old_value",
    "post_new_value_margin",
    "feedback_query_value_mean",
    "feedback_query_value_std",
    "feedback_query_value_range",
    "feedback_query_action_first_step_l2_std",
    "feedback_query_action_pairwise_l2_mean",
    "feedback_query_future_proprio_std_mean",
    "feedback_query_future_image_pixel_std_mean",
    "feedback_query_latent_action_copy_std_mean_mean_over_samples",
    "feedback_query_latent_future_proprio_copy_std_mean_mean_over_samples",
    "feedback_query_latent_value_element_std_mean_mean_over_samples",
)

FORBIDDEN_FEATURE_FRAGMENTS = (
    "terminal_",
    "failure_type",
    "local_success",
    "observed_",
    "actual_object",
    "endpoint_",
    "terminal_effect",
    "open_success",
    "feedback_success",
)


@dataclass(frozen=True)
class ModelSpec:
    name: str
    stage: str
    features: tuple[str, ...]
    alpha: float


def _unique(values: Iterable[str]) -> tuple[str, ...]:
    return tuple(dict.fromkeys(values))


MODEL_SPECS = (
    ModelSpec("pre_core_a1", "pre", PRE_QUERY_CORE_FEATURES, 1.0),
    ModelSpec("pre_core_a10", "pre", PRE_QUERY_CORE_FEATURES, 10.0),
    ModelSpec(
        "pre_state_action_a10", "pre", PRE_QUERY_STATE_ACTION_FEATURES, 10.0
    ),
    ModelSpec(
        "pre_state_action_a100", "pre", PRE_QUERY_STATE_ACTION_FEATURES, 100.0
    ),
    ModelSpec(
        "pre_combined_a10",
        "pre",
        _unique(PRE_QUERY_CORE_FEATURES + PRE_QUERY_STATE_ACTION_FEATURES),
        10.0,
    ),
    ModelSpec(
        "pre_combined_a100",
        "pre",
        _unique(PRE_QUERY_CORE_FEATURES + PRE_QUERY_STATE_ACTION_FEATURES),
        100.0,
    ),
    ModelSpec("post_overlap_a1", "post", POST_QUERY_FEATURES, 1.0),
    ModelSpec("post_overlap_a10", "post", POST_QUERY_FEATURES, 10.0),
    ModelSpec(
        "post_combined_a10",
        "post",
        _unique(
            PRE_QUERY_CORE_FEATURES
            + PRE_QUERY_STATE_ACTION_FEATURES
            + POST_QUERY_FEATURES
        ),
        10.0,
    ),
    ModelSpec(
        "post_combined_a100",
        "post",
        _unique(
            PRE_QUERY_CORE_FEATURES
            + PRE_QUERY_STATE_ACTION_FEATURES
            + POST_QUERY_FEATURES
        ),
        100.0,
    ),
)


def validate_feature_manifest(specs: Sequence[ModelSpec] = MODEL_SPECS) -> None:
    """Reject branch-outcome columns before any model is fitted."""
    allowed_post_prefix = "feedback_query_"
    for spec in specs:
        if spec.stage not in {"pre", "post"}:
            raise ValueError(f"Unknown stage for {spec.name}: {spec.stage}")
        for feature in spec.features:
            lowered = feature.lower()
            if any(fragment in lowered for fragment in FORBIDDEN_FEATURE_FRAGMENTS):
                raise ValueError(f"Outcome leakage in {spec.name}: {feature}")
            if spec.stage == "pre" and feature.startswith(allowed_post_prefix):
                raise ValueError(f"Post-query feature in pre-query model: {feature}")
            if spec.stage == "pre" and feature.startswith("post_"):
                raise ValueError(f"Post-query feature in pre-query model: {feature}")


def _as_bool(series: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False).astype(bool)
    return series.astype(str).str.strip().str.lower().isin({"1", "true", "yes"})


def _safe_cosine_distance(left: np.ndarray, right: np.ndarray) -> float:
    left_flat = left.reshape(-1)
    right_flat = right.reshape(-1)
    denominator = float(np.linalg.norm(left_flat) * np.linalg.norm(right_flat))
    if denominator <= 1e-12:
        return 0.0
    return float(1.0 - np.dot(left_flat, right_flat) / denominator)


def derive_sidecar_features(path: Path, feedback_steps: int = 8) -> dict[str, float]:
    """Read only decision-time arrays from one counterfactual sidecar."""
    with np.load(path, allow_pickle=False) as payload:
        current_proprio = np.asarray(payload["current_proprio"], dtype=float).reshape(-1)
        old_index = int(np.asarray(payload["selected_max_value_idx"]).item())
        new_index = int(np.asarray(payload["feedback_requery_selected_idx"]).item())
        old_actions = np.asarray(payload["candidate_actions"], dtype=float)
        new_actions = np.asarray(payload["feedback_requery_actions"], dtype=float)
        old_values = np.asarray(payload["candidate_values"], dtype=float)
        new_values = np.asarray(payload["feedback_requery_values"], dtype=float)

    if new_index < 0:
        raise ValueError(f"Sidecar has no feedback re-query: {path}")
    old_tail = old_actions[old_index, feedback_steps : 2 * feedback_steps]
    new_prefix = new_actions[new_index, : len(old_tail)]
    if len(old_tail) == 0 or old_tail.shape != new_prefix.shape:
        raise ValueError(
            f"Cannot align old tail {old_tail.shape} and new prefix {new_prefix.shape}: {path}"
        )
    difference = old_tail - new_prefix
    step_l2 = np.linalg.norm(difference, axis=1)
    sorted_values = np.sort(new_values[np.isfinite(new_values)])
    value_margin = (
        float(sorted_values[-1] - sorted_values[-2]) if len(sorted_values) >= 2 else 0.0
    )
    result = {
        "post_tail_l2_mean": float(step_l2.mean()),
        "post_tail_l2_max": float(step_l2.max()),
        "post_tail_first_l2": float(step_l2[0]),
        "post_tail_xyz_l2_mean": float(np.linalg.norm(difference[:, :3], axis=1).mean()),
        "post_tail_rot_l2_mean": float(np.linalg.norm(difference[:, 3:6], axis=1).mean()),
        "post_tail_gripper_abs_mean": float(np.abs(difference[:, 6]).mean()),
        "post_tail_cosine_distance": _safe_cosine_distance(old_tail, new_prefix),
        "post_tail_sign_disagreement": float(
            np.mean(np.signbit(old_tail) != np.signbit(new_prefix))
        ),
        "post_new_minus_old_value": float(new_values[new_index] - old_values[old_index]),
        "post_new_value_margin": value_margin,
    }
    for index in range(9):
        result[f"pre_current_proprio_d{index}"] = (
            float(current_proprio[index]) if index < len(current_proprio) else float("nan")
        )
    return result


def _sidecar_path(campaign_dir: Path, row: object) -> Path:
    source_run = str(getattr(row, "source_run"))
    sidecar_name = Path(str(getattr(row, "sidecar_path"))).name
    return campaign_dir / "runs" / f"{source_run}__snapshots" / sidecar_name


def _prepare_cohort(
    paired_path: Path,
    campaign_dir: Path,
    *,
    cohort: str,
    condition_id: str,
) -> pd.DataFrame:
    frame = pd.read_parquet(paired_path)
    if "condition_id" in frame:
        frame = frame.loc[frame["condition_id"].eq(condition_id)].copy()
    else:
        frame = frame.loc[
            frame["source_run"].astype(str).str.endswith(f"__{condition_id}")
        ].copy()
    if frame.empty:
        raise ValueError(f"No {condition_id} rows in {paired_path}")

    frame["open_success"] = _as_bool(frame["open_terminal_success"])
    frame["feedback_success"] = _as_bool(frame["feedback_terminal_success"])
    frame["terminal_effect"] = (
        frame["feedback_success"].astype(int) - frame["open_success"].astype(int)
    )
    replay_error = pd.to_numeric(frame["main_open_replay_state_max_abs"], errors="coerce")
    frame["strict_integrity"] = replay_error.le(REPLAY_INTEGRITY_THRESHOLD)
    frame = frame.loc[frame["strict_integrity"]].reset_index(drop=True)
    frame["cohort"] = cohort
    frame["independent_group"] = (
        cohort + "|init" + frame["init_state_id"].astype(int).astype(str)
    )
    frame["analysis_row_id"] = (
        cohort
        + "|"
        + frame["init_state_id"].astype(int).astype(str)
        + "|"
        + frame["rollout_id"].astype(int).astype(str)
    )
    sidecar_rows = []
    for row in frame.itertuples(index=False):
        path = _sidecar_path(campaign_dir, row)
        if not path.is_file():
            raise FileNotFoundError(path)
        feedback_steps = int(getattr(row, "feedback_steps", 8))
        sidecar_rows.append(derive_sidecar_features(path, feedback_steps=feedback_steps))
    return pd.concat([frame, pd.DataFrame(sidecar_rows)], axis=1)


@dataclass
class RidgeModel:
    median: np.ndarray
    mean: np.ndarray
    scale: np.ndarray
    active: np.ndarray
    coefficients: np.ndarray
    covariance: np.ndarray
    residual_scale: float


def _numeric_matrix(frame: pd.DataFrame, features: Sequence[str]) -> np.ndarray:
    missing = [feature for feature in features if feature not in frame]
    if missing:
        raise ValueError(f"Missing model features: {missing}")
    return frame.loc[:, list(features)].apply(pd.to_numeric, errors="coerce").to_numpy(float)


def fit_ridge_model(
    values: np.ndarray, target: np.ndarray, *, alpha: float
) -> RidgeModel:
    finite_columns = np.isfinite(values).any(axis=0)
    if not finite_columns.any():
        raise ValueError("No finite model features")
    selected = values[:, finite_columns]
    median = np.nanmedian(selected, axis=0)
    median = np.where(np.isfinite(median), median, 0.0)
    selected = np.where(np.isfinite(selected), selected, median)
    mean = selected.mean(axis=0)
    scale = selected.std(axis=0)
    varying = scale > 1e-10
    if not varying.any():
        varying[:] = True
        scale[:] = 1.0
    selected = selected[:, varying]
    median = median[varying]
    mean = mean[varying]
    scale = scale[varying]
    standardized = (selected - mean) / scale
    design = np.column_stack([np.ones(len(standardized)), standardized])
    penalty = np.eye(design.shape[1]) * float(alpha)
    penalty[0, 0] = 0.0
    covariance = np.linalg.pinv(design.T @ design + penalty)
    coefficients = covariance @ design.T @ target
    residual = target - design @ coefficients
    residual_scale = float(np.sqrt(np.mean(residual**2)))
    active = np.flatnonzero(finite_columns)[varying]
    return RidgeModel(
        median=median,
        mean=mean,
        scale=scale,
        active=active,
        coefficients=coefficients,
        covariance=covariance,
        residual_scale=residual_scale,
    )


def predict_ridge_model(model: RidgeModel, values: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    selected = values[:, model.active]
    selected = np.where(np.isfinite(selected), selected, model.median)
    standardized = (selected - model.mean) / model.scale
    design = np.column_stack([np.ones(len(standardized)), standardized])
    mean = design @ model.coefficients
    leverage = np.einsum("ij,jk,ik->i", design, model.covariance, design)
    std = model.residual_scale * np.sqrt(np.maximum(1.0 + leverage, 0.0))
    return mean, std


def grouped_oof_predictions(
    frame: pd.DataFrame,
    spec: ModelSpec,
    *,
    group_column: str = "independent_group",
) -> tuple[np.ndarray, np.ndarray]:
    values = _numeric_matrix(frame, spec.features)
    target = frame["terminal_effect"].to_numpy(dtype=float)
    groups = frame[group_column].astype(str).to_numpy()
    means = np.full(len(frame), np.nan, dtype=float)
    stds = np.full(len(frame), np.nan, dtype=float)
    for group in sorted(set(groups)):
        test = groups == group
        train = ~test
        if train.sum() < 8:
            continue
        model = fit_ridge_model(values[train], target[train], alpha=spec.alpha)
        means[test], stds[test] = predict_ridge_model(model, values[test])
    return means, stds


def train_transfer_predictions(
    train: pd.DataFrame, test: pd.DataFrame, spec: ModelSpec
) -> tuple[np.ndarray, np.ndarray]:
    train_values = _numeric_matrix(train, spec.features)
    test_values = _numeric_matrix(test, spec.features)
    model = fit_ridge_model(
        train_values, train["terminal_effect"].to_numpy(float), alpha=spec.alpha
    )
    return predict_ridge_model(model, test_values)


def prediction_diagnostics(
    frame: pd.DataFrame,
    means: np.ndarray,
    *,
    scope: str,
    spec: ModelSpec,
) -> dict[str, object]:
    target = frame["terminal_effect"].to_numpy(float)
    valid = np.isfinite(means)
    discordant = valid & (target != 0)
    correlation = (
        pd.Series(means[valid]).corr(pd.Series(target[valid]), method="spearman")
        if valid.sum() >= 3
        else float("nan")
    )
    return {
        "scope": scope,
        "model": spec.name,
        "stage": spec.stage,
        "alpha": spec.alpha,
        "states": int(valid.sum()),
        "groups": int(frame.loc[valid, "independent_group"].nunique()),
        "features": len(spec.features),
        "rmse": float(np.sqrt(np.mean((means[valid] - target[valid]) ** 2))),
        "spearman_effect": float(correlation),
        "rescue_vs_all_auc": binary_auc(target[valid] > 0, means[valid]),
        "rescue_vs_harm_auc": binary_auc(target[discordant] > 0, means[discordant]),
    }


def _policy_statistics(
    frame: pd.DataFrame,
    selected: np.ndarray,
    *,
    stage: str,
    query_cost: float,
) -> dict[str, object]:
    selected = np.asarray(selected, dtype=bool)
    target = frame["terminal_effect"].to_numpy(float)
    baseline = frame["open_success"].to_numpy(bool)
    query = selected if stage == "pre" else np.ones(len(frame), dtype=bool)
    contributions = selected.astype(float) * target
    adjusted = contributions - query_cost * query.astype(float)
    rescue = target > 0
    harm = target < 0
    rescue_recall = float(selected[rescue].mean()) if rescue.any() else float("nan")
    harm_avoidance = float((~selected[harm]).mean()) if harm.any() else float("nan")
    balanced_accuracy = float(np.nanmean([rescue_recall, harm_avoidance]))
    return {
        "states": len(frame),
        "selected": int(selected.sum()),
        "query_rate": float(query.mean()),
        "selected_rescues": int((selected & rescue).sum()),
        "selected_harms": int((selected & harm).sum()),
        "selected_neutral": int((selected & (target == 0)).sum()),
        "rescue_recall": rescue_recall,
        "harm_avoidance": harm_avoidance,
        "balanced_accuracy": balanced_accuracy,
        "baseline_success_rate": float(baseline.mean()),
        "method_success_rate": float((baseline.astype(float) + contributions).mean()),
        "raw_success_delta": float(contributions.mean()),
        "adjusted_success_delta": float(adjusted.mean()),
    }


def cluster_bootstrap_policy_ci(
    frame: pd.DataFrame,
    selected: np.ndarray,
    *,
    stage: str,
    query_cost: float,
    repetitions: int = DEFAULT_BOOTSTRAP_REPETITIONS,
    seed: int = DEFAULT_BOOTSTRAP_SEED,
) -> tuple[float, float]:
    selected = np.asarray(selected, dtype=bool)
    target = frame["terminal_effect"].to_numpy(float)
    query = selected if stage == "pre" else np.ones(len(frame), dtype=bool)
    contribution = selected.astype(float) * target - query_cost * query.astype(float)
    work = pd.DataFrame(
        {
            "group": frame["independent_group"].astype(str).to_numpy(),
            "sum": contribution,
            "size": 1,
        }
    ).groupby("group", sort=True)[["sum", "size"]].sum()
    values = work.to_numpy(float)
    rng = np.random.default_rng(seed)
    draws = rng.integers(0, len(values), size=(repetitions, len(values)))
    sampled = values[draws]
    effects = sampled[:, :, 0].sum(axis=1) / sampled[:, :, 1].sum(axis=1)
    return tuple(float(value) for value in np.quantile(effects, [0.025, 0.975]))


def _prediction_rows(
    frame: pd.DataFrame,
    *,
    scope: str,
    spec: ModelSpec,
    means: np.ndarray,
    stds: np.ndarray,
) -> pd.DataFrame:
    return pd.DataFrame(
        {
            "scope": scope,
            "analysis_row_id": frame["analysis_row_id"].to_numpy(),
            "cohort": frame["cohort"].to_numpy(),
            "independent_group": frame["independent_group"].to_numpy(),
            "init_state_id": frame["init_state_id"].to_numpy(),
            "rollout_id": frame["rollout_id"].to_numpy(),
            "terminal_effect": frame["terminal_effect"].to_numpy(),
            "terminal_outcome": frame["terminal_outcome"].to_numpy(),
            "model": spec.name,
            "stage": spec.stage,
            "alpha": spec.alpha,
            "predicted_vof_mean": means,
            "predicted_vof_std": stds,
        }
    )


def policy_tables(
    frame: pd.DataFrame,
    predictions: pd.DataFrame,
    *,
    scope: str,
    query_cost: float,
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    baseline_specs = (
        ("always_commit", "pre", np.zeros(len(frame), dtype=bool)),
        ("always_requery", "pre", np.ones(len(frame), dtype=bool)),
        ("oracle_pre", "pre", frame["terminal_effect"].to_numpy(float) > 0),
        ("oracle_post", "post", frame["terminal_effect"].to_numpy(float) > 0),
    )
    for name, stage, selected in baseline_specs:
        row = {
            "scope": scope,
            "model": name,
            "stage": stage,
            "selection_mode": "baseline",
            "beta": float("nan"),
            "budget": float(selected.mean()),
        }
        row.update(_policy_statistics(frame, selected, stage=stage, query_cost=query_cost))
        rows.append(row)

    for model_name, model_predictions in predictions.groupby("model", sort=True):
        stage = str(model_predictions["stage"].iloc[0])
        ordered = frame[["analysis_row_id"]].merge(
            model_predictions[
                ["analysis_row_id", "predicted_vof_mean", "predicted_vof_std"]
            ],
            on="analysis_row_id",
            how="left",
            validate="one_to_one",
        )
        mean = ordered["predicted_vof_mean"].to_numpy(float)
        std = ordered["predicted_vof_std"].to_numpy(float)
        for beta in DEFAULT_BETAS:
            score = mean - beta * std
            natural_threshold = query_cost if stage == "pre" else 0.0
            selected = np.isfinite(score) & (score > natural_threshold)
            row = {
                "scope": scope,
                "model": model_name,
                "stage": stage,
                "selection_mode": "lcb_threshold",
                "beta": beta,
                "budget": float(selected.mean()),
            }
            row.update(
                _policy_statistics(frame, selected, stage=stage, query_cost=query_cost)
            )
            rows.append(row)
            valid = np.flatnonzero(np.isfinite(score))
            for budget in DEFAULT_BUDGETS:
                count = min(len(valid), max(1, int(math.ceil(len(frame) * budget))))
                selected = np.zeros(len(frame), dtype=bool)
                if count:
                    order = valid[np.argsort(score[valid], kind="mergesort")]
                    selected[order[-count:]] = True
                row = {
                    "scope": scope,
                    "model": model_name,
                    "stage": stage,
                    "selection_mode": "ranked_budget",
                    "beta": beta,
                    "budget": budget,
                }
                row.update(
                    _policy_statistics(frame, selected, stage=stage, query_cost=query_cost)
                )
                rows.append(row)
    return pd.DataFrame(rows)


def _selected_mask_from_policy(
    frame: pd.DataFrame, predictions: pd.DataFrame, policy: pd.Series
) -> np.ndarray:
    scoped = predictions.loc[predictions["model"].eq(policy["model"])]
    ordered = frame[["analysis_row_id"]].merge(
        scoped[["analysis_row_id", "predicted_vof_mean", "predicted_vof_std"]],
        on="analysis_row_id",
        how="left",
        validate="one_to_one",
    )
    score = ordered["predicted_vof_mean"].to_numpy(float) - float(policy["beta"]) * ordered[
        "predicted_vof_std"
    ].to_numpy(float)
    if policy["selection_mode"] == "lcb_threshold":
        threshold = DEFAULT_QUERY_COST if policy["stage"] == "pre" else 0.0
        return np.isfinite(score) & (score > threshold)
    valid = np.flatnonzero(np.isfinite(score))
    count = min(len(valid), max(1, int(math.ceil(len(frame) * float(policy["budget"])))))
    selected = np.zeros(len(frame), dtype=bool)
    order = valid[np.argsort(score[valid], kind="mergesort")]
    selected[order[-count:]] = True
    return selected


def _best_development_policy(policies: pd.DataFrame, *, stage: str) -> pd.Series:
    candidates = policies.loc[
        policies["stage"].eq(stage)
        & policies["selection_mode"].eq("ranked_budget")
        & ~policies["model"].str.startswith("oracle")
    ].copy()
    return candidates.sort_values(
        ["adjusted_success_delta", "selected_harms", "query_rate", "model", "beta"],
        ascending=[False, True, True, True, True],
    ).iloc[0]


def _permuted_group_target(frame: pd.DataFrame, rng: np.random.Generator) -> np.ndarray:
    """Permute complete rollout vectors between equally sized init groups."""
    groups = {
        key: np.asarray(list(index), dtype=int)
        for key, index in frame.groupby("independent_group", sort=True).groups.items()
    }
    target = frame["terminal_effect"].to_numpy(float)
    permuted = np.empty_like(target)
    by_size: dict[int, list[str]] = {}
    for key, index in groups.items():
        by_size.setdefault(len(index), []).append(key)
    for keys in by_size.values():
        sources = list(keys)
        rng.shuffle(sources)
        for destination, source in zip(keys, sources):
            permuted[groups[destination]] = target[groups[source]]
    return permuted


def _maximum_prequery_search_gain(
    frame: pd.DataFrame, *, query_cost: float
) -> float:
    best = -float("inf")
    target = frame["terminal_effect"].to_numpy(float)
    pre_specs = [spec for spec in MODEL_SPECS if spec.stage == "pre"]
    for spec in pre_specs:
        mean, std = grouped_oof_predictions(frame, spec)
        for beta in DEFAULT_BETAS:
            score = mean - beta * std
            valid = np.flatnonzero(np.isfinite(score))
            for budget in DEFAULT_BUDGETS:
                count = min(len(valid), max(1, int(math.ceil(len(frame) * budget))))
                order = valid[np.argsort(score[valid], kind="mergesort")]
                selected = np.zeros(len(frame), dtype=bool)
                selected[order[-count:]] = True
                gain = float(
                    np.mean(selected.astype(float) * target)
                    - query_cost * selected.mean()
                )
                best = max(best, gain)
    return best


def selected_model_permutation_test(
    frame: pd.DataFrame,
    *,
    observed_gain: float,
    query_cost: float,
    repetitions: int,
    seed: int,
) -> dict[str, object]:
    """Family-wise null for the complete pre-query model/beta/budget search."""
    rng = np.random.default_rng(seed)
    null = np.empty(repetitions, dtype=float)
    original = frame["terminal_effect"].to_numpy(float).copy()
    work = frame.copy()
    for repetition in range(repetitions):
        work["terminal_effect"] = _permuted_group_target(frame, rng)
        null[repetition] = _maximum_prequery_search_gain(work, query_cost=query_cost)
    work["terminal_effect"] = original
    exceedances = int(np.sum(null >= observed_gain - 1e-12))
    return {
        "repetitions": repetitions,
        "seed": seed,
        "observed_best_adjusted_gain": observed_gain,
        "null_mean_best_adjusted_gain": float(null.mean()),
        "null_p95_best_adjusted_gain": float(np.quantile(null, 0.95)),
        "exceedances": exceedances,
        "familywise_pvalue": float((exceedances + 1) / (repetitions + 1)),
        "null_distribution": null,
    }


def fixed_policy_randomization_test(
    frame: pd.DataFrame,
    selected: np.ndarray,
    *,
    stage: str,
    query_cost: float,
    repetitions: int,
    seed: int,
) -> dict[str, object]:
    """Randomization test for a selection mask fixed without target-cohort labels."""
    selected = np.asarray(selected, dtype=bool)
    observed = float(
        np.mean(selected * frame["terminal_effect"].to_numpy(float))
        - query_cost * (selected.mean() if stage == "pre" else 1.0)
    )
    rng = np.random.default_rng(seed)
    null = np.empty(repetitions, dtype=float)
    for repetition in range(repetitions):
        target = _permuted_group_target(frame, rng)
        null[repetition] = float(
            np.mean(selected * target)
            - query_cost * (selected.mean() if stage == "pre" else 1.0)
        )
    exceedances = int(np.sum(null >= observed - 1e-12))
    return {
        "repetitions": repetitions,
        "seed": seed,
        "observed_adjusted_gain": observed,
        "null_mean_adjusted_gain": float(null.mean()),
        "null_p95_adjusted_gain": float(np.quantile(null, 0.95)),
        "exceedances": exceedances,
        "randomization_pvalue": float((exceedances + 1) / (repetitions + 1)),
        "null_distribution": null,
    }


def _screen_selected_transfer(
    screen: pd.DataFrame,
    holdout: pd.DataFrame,
    screen_predictions: pd.DataFrame,
    holdout_transfer_predictions: pd.DataFrame,
    screen_policies: pd.DataFrame,
    *,
    stage: str,
    query_cost: float,
) -> tuple[dict[str, object], np.ndarray]:
    chosen = _best_development_policy(screen_policies, stage=stage)
    model = str(chosen["model"])
    beta = float(chosen["beta"])
    budget = float(chosen["budget"])
    scoped = holdout_transfer_predictions.loc[
        holdout_transfer_predictions["model"].eq(model)
    ]
    ordered = holdout[["analysis_row_id"]].merge(
        scoped[["analysis_row_id", "predicted_vof_mean", "predicted_vof_std"]],
        on="analysis_row_id",
        how="left",
        validate="one_to_one",
    )
    score = ordered["predicted_vof_mean"].to_numpy(float) - beta * ordered[
        "predicted_vof_std"
    ].to_numpy(float)
    valid = np.flatnonzero(np.isfinite(score))
    count = min(len(valid), max(1, int(math.ceil(len(holdout) * budget))))
    selected = np.zeros(len(holdout), dtype=bool)
    order = valid[np.argsort(score[valid], kind="mergesort")]
    selected[order[-count:]] = True
    result = {
        "source_scope": "screen_loio",
        "target_scope": "screen_to_holdout",
        "model": model,
        "stage": stage,
        "beta": beta,
        "budget": budget,
    }
    result.update(
        _policy_statistics(holdout, selected, stage=stage, query_cost=query_cost)
    )
    ci_low, ci_high = cluster_bootstrap_policy_ci(
        holdout, selected, stage=stage, query_cost=query_cost
    )
    result["adjusted_ci_low"] = ci_low
    result["adjusted_ci_high"] = ci_high
    return result, selected


def _feature_manifest() -> dict[str, object]:
    return {
        "target": "feedback_terminal_success - open_terminal_success",
        "pre_query_timing": "available at original query 4 before the extra model call",
        "post_query_timing": "available after re-query generation but before either tail executes",
        "explicitly_forbidden": list(FORBIDDEN_FEATURE_FRAGMENTS),
        "forbidden_sidecar_arrays": [
            "candidate_endpoint_*",
            "feedback_endpoint_*",
            "candidate_h32_endpoint_*",
            "feedback_h32_endpoint_*",
        ],
        "models": [
            {
                "name": spec.name,
                "stage": spec.stage,
                "alpha": spec.alpha,
                "features": list(spec.features),
            }
            for spec in MODEL_SPECS
        ],
    }


def _make_plot(
    holdout: pd.DataFrame,
    holdout_predictions: pd.DataFrame,
    holdout_policies: pd.DataFrame,
    best_pre: pd.Series,
    best_post: pd.Series,
    transfer_rows: pd.DataFrame,
    output_path: Path,
) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    colors = {
        "both_fail": "#777777",
        "both_success": "#3f6ea8",
        "harm": "#bd3f3f",
        "rescue": "#25865a",
    }
    for axis, chosen, title in (
        (axes[0, 0], best_pre, "Best pre-query OOF score"),
        (axes[0, 1], best_post, "Best post-query OOF score"),
    ):
        scoped = holdout_predictions.loc[
            holdout_predictions["model"].eq(chosen["model"])
        ]
        merged = holdout[["analysis_row_id", "terminal_outcome"]].merge(
            scoped[["analysis_row_id", "predicted_vof_mean", "predicted_vof_std"]],
            on="analysis_row_id",
            validate="one_to_one",
        )
        score = merged["predicted_vof_mean"] - float(chosen["beta"]) * merged[
            "predicted_vof_std"
        ]
        order = ["both_fail", "both_success", "harm", "rescue"]
        for index, outcome in enumerate(order):
            values = score.loc[merged["terminal_outcome"].eq(outcome)].to_numpy(float)
            jitter = np.linspace(-0.12, 0.12, len(values)) if len(values) else np.array([])
            axis.scatter(
                np.full(len(values), index) + jitter,
                values,
                color=colors[outcome],
                alpha=0.85,
                label=outcome,
            )
        axis.axhline(0, color="black", linewidth=1)
        axis.set_xticks(range(len(order)), [value.replace("_", "\n") for value in order])
        axis.set_ylabel("OOF signed-VoF score")
        axis.set_title(f"{title}: {chosen['model']}, beta={chosen['beta']}")
        axis.grid(axis="y", alpha=0.25)

    axis = axes[1, 0]
    for chosen, label, color in (
        (best_pre, "pre-query", "#25865a"),
        (best_post, "post-query", "#7b5ea7"),
    ):
        curve = holdout_policies.loc[
            holdout_policies["model"].eq(chosen["model"])
            & holdout_policies["stage"].eq(chosen["stage"])
            & holdout_policies["selection_mode"].eq("ranked_budget")
            & holdout_policies["beta"].eq(chosen["beta"])
        ].sort_values("budget")
        axis.plot(
            100 * curve["budget"],
            100 * curve["adjusted_success_delta"],
            marker="o",
            color=color,
            label=label,
        )
    axis.axhline(0, color="black", linewidth=1)
    axis.set_xlabel("selected-tail budget (%)")
    axis.set_ylabel("cost-adjusted terminal gain (pp)")
    axis.set_title("Holdout-cohort grouped OOF budget curves")
    axis.grid(alpha=0.25)
    axis.legend()

    axis = axes[1, 1]
    labels = ["commit", "always\nrequery", "best pre\nOOF", "best post\nOOF"]
    always = holdout_policies.loc[holdout_policies["model"].eq("always_requery")].iloc[0]
    values = [
        0.0,
        100 * float(always["adjusted_success_delta"]),
        100 * float(best_pre["adjusted_success_delta"]),
        100 * float(best_post["adjusted_success_delta"]),
    ]
    bars = axis.bar(labels, values, color=["#666666", "#c58b36", "#25865a", "#7b5ea7"])
    axis.axhline(0, color="black", linewidth=1)
    axis.set_ylabel("cost-adjusted terminal gain (pp)")
    axis.set_title("Development policy comparison")
    for bar, value in zip(bars, values):
        axis.text(bar.get_x() + bar.get_width() / 2, value, f"{value:+.1f}", ha="center", va="bottom")
    transfer_text = "\n".join(
        f"screen->holdout {row.stage}: {100 * row.adjusted_success_delta:+.1f} pp"
        for row in transfer_rows.itertuples(index=False)
    )
    axis.text(0.02, 0.98, transfer_text, transform=axis.transAxes, va="top", fontsize=9)
    axis.grid(axis="y", alpha=0.25)

    fig.suptitle("Position y0.2 signed value-of-feedback development", fontsize=16)
    fig.tight_layout()
    fig.savefig(output_path, dpi=180)
    plt.close(fig)


def _format_policy(policy: pd.Series | dict[str, object]) -> str:
    get = policy.get
    return (
        f"`{get('model')}` ({get('stage')}, beta={float(get('beta')):.1f}, "
        f"budget={100 * float(get('budget')):.0f}%): "
        f"{int(get('selected_rescues'))} rescue / {int(get('selected_harms'))} harm, "
        f"adjusted delta {100 * float(get('adjusted_success_delta')):+.1f} pp"
    )


def write_report(
    output_dir: Path,
    screen: pd.DataFrame,
    holdout: pd.DataFrame,
    diagnostics: pd.DataFrame,
    best_pre: pd.Series,
    best_post: pd.Series,
    transfer: pd.DataFrame,
    permutation: dict[str, object],
    transfer_randomization: dict[str, object],
    gate: dict[str, object],
) -> None:
    lines = [
        "# Position y0.2 signed-VoF router: leakage-safe development",
        "",
        "## Status",
        "",
        "This is a post-holdout development analysis. It may authorize new data collection,",
        "but it is not confirmatory evidence for a selector.",
        "",
        f"- Screen cohort: **{len(screen)}** states / **{screen['independent_group'].nunique()}** init groups.",
        f"- Former holdout cohort: **{len(holdout)}** states / **{holdout['independent_group'].nunique()}** init groups.",
        f"- Former holdout rescue / harm: **{int((holdout['terminal_effect'] > 0).sum())} / {int((holdout['terminal_effect'] < 0).sum())}**.",
        f"- Opportunity gate: **{'PASS' if gate['passed'] else 'FAIL'}**.",
        "",
        "## Target and online decision",
        "",
        "$$",
        "Y_i=\\mathbb{1}[success_{feedback}]-\\mathbb{1}[success_{commit}]\\in\\{-1,0,+1\\}.",
        "$$",
        "",
        "The pre-query router pays for feedback only when its conservative score is positive:",
        "",
        "$$",
        "\\hat\\mu_{VoF}(x)-\\beta\\hat\\sigma_{VoF}(x)-c_{query}>0.",
        "$$",
        "",
        "The post-query selector may compare the old action tail with the newly generated",
        "prefix, but query cost is charged on every evaluated state.",
        "",
        "## Best grouped OOF development policies",
        "",
        f"- Pre-query: {_format_policy(best_pre)}.",
        f"- Post-query: {_format_policy(best_post)}.",
        "",
        "These are selected from several model/budget combinations on development labels and",
        "must be interpreted as optimistic discovery estimates.",
        "",
        "The family-wise group-permutation test repeats the complete pre-query",
        "model/beta/budget search. Its p-value is",
        f"**{float(permutation['familywise_pvalue']):.4f}** (null 95th percentile",
        f"{100 * float(permutation['null_p95_best_adjusted_gain']):+.1f} pp).",
        "",
        "## Screen-to-former-holdout diagnostic",
        "",
        transfer.to_markdown(index=False),
        "",
        "The budget and model in each row were chosen using only screen-cohort OOF labels;",
        "the outcomes in the target cohort were not used for that row's ranking choice.",
        "Because the feature families themselves were designed after viewing the holdout, this",
        "still remains exploratory rather than a recovered confirmatory test.",
        f"The fixed-mask target-cohort randomization p-value for the pre-query row is **{float(transfer_randomization['randomization_pvalue']):.4f}**.",
        "",
        "## Prediction diagnostics",
        "",
        diagnostics.loc[diagnostics["scope"].eq("holdout_loio")]
        .sort_values("rescue_vs_harm_auc", ascending=False)
        .to_markdown(index=False),
        "",
        "## Leakage audit",
        "",
        "`feedback_endpoint_*` and every realized local/terminal branch metric are excluded.",
        "Those endpoint arrays were saved after the new tail executed and would leak the",
        "intervention outcome. Pre-query models use only original q4 outputs and current",
        "proprio. Post-query models add only newly generated actions/value and old-tail versus",
        "new-prefix disagreement, all available before the chosen tail executes.",
        "",
        "## Decision",
        "",
        str(gate["decision"]),
        "",
        "A PASS permits a targeted boundary collection and freezing a compact router. It does",
        "not permit a success claim. A new task/init split remains mandatory.",
    ]
    (output_dir / "RESULTS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--screen-campaign", type=Path, required=True)
    parser.add_argument("--holdout-campaign", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--condition-id", default="position_y0p2_task0")
    parser.add_argument("--query-cost", type=float, default=DEFAULT_QUERY_COST)
    parser.add_argument("--permutation-repetitions", type=int, default=1_000)
    parser.add_argument("--permutation-seed", type=int, default=20260903)
    args = parser.parse_args()

    validate_feature_manifest()
    screen_campaign = args.screen_campaign.expanduser().resolve()
    holdout_campaign = args.holdout_campaign.expanduser().resolve()
    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    screen = _prepare_cohort(
        screen_campaign / "analysis" / "cross_factor_boundary" / "paired_outcomes.parquet",
        screen_campaign,
        cohort="screen_init0_19",
        condition_id=args.condition_id,
    )
    holdout = _prepare_cohort(
        holdout_campaign
        / "analysis"
        / "position_direction_holdout"
        / "paired_outcomes.parquet",
        holdout_campaign,
        cohort="former_holdout_init20_49",
        condition_id=args.condition_id,
    )
    pooled = pd.concat([screen, holdout], ignore_index=True)

    prediction_frames = []
    diagnostics_rows = []
    scope_frames = {
        "screen_loio": screen,
        "holdout_loio": holdout,
        "pooled_loio": pooled,
    }
    for scope, frame in scope_frames.items():
        for spec in MODEL_SPECS:
            means, stds = grouped_oof_predictions(frame, spec)
            prediction_frames.append(
                _prediction_rows(
                    frame, scope=scope, spec=spec, means=means, stds=stds
                )
            )
            diagnostics_rows.append(
                prediction_diagnostics(frame, means, scope=scope, spec=spec)
            )

    transfer_prediction_frames = []
    for spec in MODEL_SPECS:
        means, stds = train_transfer_predictions(screen, holdout, spec)
        transfer_prediction_frames.append(
            _prediction_rows(
                holdout,
                scope="screen_to_holdout",
                spec=spec,
                means=means,
                stds=stds,
            )
        )
        diagnostics_rows.append(
            prediction_diagnostics(
                holdout, means, scope="screen_to_holdout", spec=spec
            )
        )

    predictions = pd.concat(prediction_frames, ignore_index=True)
    transfer_predictions = pd.concat(transfer_prediction_frames, ignore_index=True)
    diagnostics = pd.DataFrame(diagnostics_rows)
    policy_frames = []
    for scope, frame in scope_frames.items():
        policy_frames.append(
            policy_tables(
                frame,
                predictions.loc[predictions["scope"].eq(scope)],
                scope=scope,
                query_cost=args.query_cost,
            )
        )
    policies = pd.concat(policy_frames, ignore_index=True)
    holdout_policies = policies.loc[policies["scope"].eq("holdout_loio")]
    screen_policies = policies.loc[policies["scope"].eq("screen_loio")]
    best_pre = _best_development_policy(holdout_policies, stage="pre")
    best_post = _best_development_policy(holdout_policies, stage="post")

    transfer_results = [
        _screen_selected_transfer(
                screen,
                holdout,
                predictions.loc[predictions["scope"].eq("screen_loio")],
                transfer_predictions,
                screen_policies,
                stage=stage,
                query_cost=args.query_cost,
            )
            for stage in ("pre", "post")
    ]
    transfer_rows = pd.DataFrame([result for result, _mask in transfer_results])
    transfer_masks = {
        str(result["stage"]): mask for result, mask in transfer_results
    }

    holdout_predictions = predictions.loc[predictions["scope"].eq("holdout_loio")]
    best_pre_mask = _selected_mask_from_policy(holdout, holdout_predictions, best_pre)
    best_post_mask = _selected_mask_from_policy(holdout, holdout_predictions, best_post)
    pre_ci = cluster_bootstrap_policy_ci(
        holdout,
        best_pre_mask,
        stage="pre",
        query_cost=args.query_cost,
    )
    post_ci = cluster_bootstrap_policy_ci(
        holdout,
        best_post_mask,
        stage="post",
        query_cost=args.query_cost,
    )
    best_pre = best_pre.copy()
    best_post = best_post.copy()
    best_pre["adjusted_ci_low"], best_pre["adjusted_ci_high"] = pre_ci
    best_post["adjusted_ci_low"], best_post["adjusted_ci_high"] = post_ci

    transfer_pre = transfer_rows.loc[transfer_rows["stage"].eq("pre")].iloc[0]
    permutation = selected_model_permutation_test(
        holdout,
        observed_gain=float(best_pre["adjusted_success_delta"]),
        query_cost=args.query_cost,
        repetitions=args.permutation_repetitions,
        seed=args.permutation_seed,
    )
    permutation_null = np.asarray(permutation.pop("null_distribution"), dtype=float)
    pd.DataFrame({"null_best_adjusted_gain": permutation_null}).to_csv(
        output_dir / "prequery_search_permutation_null.csv", index=False
    )
    transfer_randomization = fixed_policy_randomization_test(
        holdout,
        transfer_masks["pre"],
        stage="pre",
        query_cost=args.query_cost,
        repetitions=max(10_000, args.permutation_repetitions),
        seed=args.permutation_seed + 1,
    )
    transfer_null = np.asarray(
        transfer_randomization.pop("null_distribution"), dtype=float
    )
    pd.DataFrame({"null_adjusted_gain": transfer_null}).to_csv(
        output_dir / "screen_transfer_randomization_null.csv", index=False
    )
    gate_checks = {
        "holdout_oof_adjusted_gain_at_least_5pp": float(
            best_pre["adjusted_success_delta"]
        )
        >= 0.05,
        "holdout_oof_ci_lower_positive": float(best_pre["adjusted_ci_low"]) > 0.0,
        "holdout_oof_at_least_five_rescues": int(best_pre["selected_rescues"]) >= 5,
        "holdout_oof_harms_at_most_two": int(best_pre["selected_harms"]) <= 2,
        "screen_selected_transfer_positive": float(
            transfer_pre["adjusted_success_delta"]
        )
        > 0.0,
        "screen_selected_transfer_rescues_exceed_harms": int(
            transfer_pre["selected_rescues"]
        )
        > int(transfer_pre["selected_harms"]),
        "holdout_search_familywise_permutation_p_below_0p05": float(
            permutation["familywise_pvalue"]
        )
        < 0.05,
        "screen_transfer_randomization_p_below_0p05": float(
            transfer_randomization["randomization_pvalue"]
        )
        < 0.05,
    }
    gate = {
        "checks": gate_checks,
        "passed": bool(all(gate_checks.values())),
        "decision": (
            "advance_to_targeted_boundary_collection_and_freeze_after_development"
            if all(gate_checks.values())
            else "do_not_freeze_router; collect_or_change_representation"
        ),
        "best_pre_policy": best_pre.to_dict(),
        "best_post_policy": best_post.to_dict(),
    }

    dataset_columns = [
        "analysis_row_id",
        "cohort",
        "independent_group",
        "init_state_id",
        "rollout_id",
        "rollout_seed",
        "open_success",
        "feedback_success",
        "terminal_effect",
        "terminal_outcome",
    ] + list(
        _unique(
            PRE_QUERY_CORE_FEATURES
            + PRE_QUERY_STATE_ACTION_FEATURES
            + POST_QUERY_FEATURES
        )
    )
    pooled.loc[:, dataset_columns].to_parquet(
        output_dir / "signed_vof_dataset.parquet", index=False
    )
    pooled.loc[:, dataset_columns].to_csv(
        output_dir / "signed_vof_dataset.csv", index=False
    )
    predictions.to_parquet(output_dir / "grouped_oof_predictions.parquet", index=False)
    predictions.to_csv(output_dir / "grouped_oof_predictions.csv", index=False)
    transfer_predictions.to_parquet(
        output_dir / "screen_to_holdout_predictions.parquet", index=False
    )
    diagnostics.to_csv(output_dir / "prediction_diagnostics.csv", index=False)
    policies.to_csv(output_dir / "policy_budget_curves.csv", index=False)
    transfer_rows.to_csv(output_dir / "screen_selected_transfer.csv", index=False)
    (output_dir / "feature_manifest.json").write_text(
        json.dumps(_feature_manifest(), indent=2), encoding="utf-8"
    )
    (output_dir / "gate.json").write_text(json.dumps(gate, indent=2), encoding="utf-8")
    (output_dir / "permutation_test.json").write_text(
        json.dumps(permutation, indent=2), encoding="utf-8"
    )
    (output_dir / "screen_transfer_randomization_test.json").write_text(
        json.dumps(transfer_randomization, indent=2), encoding="utf-8"
    )

    _make_plot(
        holdout,
        holdout_predictions,
        holdout_policies,
        best_pre,
        best_post,
        transfer_rows,
        output_dir / "signed_vof_router_summary.png",
    )
    write_report(
        output_dir,
        screen,
        holdout,
        diagnostics,
        best_pre,
        best_post,
        transfer_rows,
        permutation,
        transfer_randomization,
        gate,
    )
    summary = {
        "screen_states": len(screen),
        "holdout_states": len(holdout),
        "pooled_states": len(pooled),
        "holdout_rescues": int((holdout["terminal_effect"] > 0).sum()),
        "holdout_harms": int((holdout["terminal_effect"] < 0).sum()),
        "best_pre_policy": best_pre.to_dict(),
        "best_post_policy": best_post.to_dict(),
        "screen_selected_transfer": transfer_rows.to_dict(orient="records"),
        "prequery_search_permutation": permutation,
        "screen_transfer_randomization": transfer_randomization,
        "gate": gate,
        "output_dir": str(output_dir),
    }
    (output_dir / "summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
