#!/usr/bin/env bash
set -euo pipefail

# Natural paired search: no action intervention.
# Repeats the same task/init with different rollout seeds until a natural
# success/fail pair is found, or until max rollouts are exhausted.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

LIBERO_PRO_PAIRED_RUN_NAME="${LIBERO_PRO_NATURAL_PAIR_RUN_NAME:-natural_fail_same_init_lan_search}" \
LIBERO_PRO_PAIRED_SUITES="${LIBERO_PRO_NATURAL_PAIR_SUITES:-libero_spatial_lan}" \
LIBERO_PRO_PAIRED_TASK_IDS="${LIBERO_PRO_NATURAL_PAIR_TASK_IDS:-0,2}" \
LIBERO_PRO_PAIRED_INIT_STATE_IDS="${LIBERO_PRO_NATURAL_PAIR_INIT_STATE_IDS:-0,1}" \
LIBERO_PRO_PAIRED_MAX_ROLLOUTS_PER_INIT="${LIBERO_PRO_NATURAL_PAIR_MAX_ROLLOUTS:-16}" \
LIBERO_PRO_PAIRED_MIN_SUCCESS="${LIBERO_PRO_NATURAL_PAIR_MIN_SUCCESS:-1}" \
LIBERO_PRO_PAIRED_MIN_FAILED="${LIBERO_PRO_NATURAL_PAIR_MIN_FAILED:-1}" \
LIBERO_PRO_PAIRED_BASE_SEED="${LIBERO_PRO_NATURAL_PAIR_BASE_SEED:-195}" \
LIBERO_PRO_PAIRED_ROLLOUT_SEED_STEP="${LIBERO_PRO_NATURAL_PAIR_ROLLOUT_SEED_STEP:-97}" \
LIBERO_PRO_PAIRED_UNCERTAINTY_SEEDS="${LIBERO_PRO_NATURAL_PAIR_UNCERTAINTY_SEEDS:-0,1,2,3}" \
LIBERO_PRO_PAIRED_MAX_TIMESTEPS="${LIBERO_PRO_NATURAL_PAIR_MAX_TIMESTEPS:-220}" \
LIBERO_PRO_PAIRED_SAVE_VIDEOS="${LIBERO_PRO_NATURAL_PAIR_SAVE_VIDEOS:-0}" \
LIBERO_PRO_PAIRED_VIDEO_DIR="${LIBERO_PRO_NATURAL_PAIR_VIDEO_DIR:-../experiments/uncertainty/${LIBERO_PRO_NATURAL_PAIR_RUN_NAME:-natural_fail_same_init_lan_search}__videos}" \
"$SCRIPT_DIR/run_libero_pro_paired_prediction_collect.sh"
