#!/usr/bin/env bash
set -euo pipefail

# Natural success/fail grid: no action intervention.
# Mixes easy, language-OOD, relation-swap, and task-semantic variants so the
# same policy naturally produces both successes and failures.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

LIBERO_PRO_PAIRED_RUN_NAME="${LIBERO_PRO_NATURAL_FAIL_RUN_NAME:-natural_fail_mixed_grid}" \
LIBERO_PRO_PAIRED_SUITES="${LIBERO_PRO_NATURAL_FAIL_SUITES:-libero_spatial_object,libero_spatial_lan,libero_spatial_swap,libero_spatial_task}" \
LIBERO_PRO_PAIRED_TASK_IDS="${LIBERO_PRO_NATURAL_FAIL_TASK_IDS:-0}" \
LIBERO_PRO_PAIRED_INIT_STATE_IDS="${LIBERO_PRO_NATURAL_FAIL_INIT_STATE_IDS:-0}" \
LIBERO_PRO_PAIRED_MAX_ROLLOUTS_PER_INIT="${LIBERO_PRO_NATURAL_FAIL_MAX_ROLLOUTS:-4}" \
LIBERO_PRO_PAIRED_MIN_SUCCESS="${LIBERO_PRO_NATURAL_FAIL_MIN_SUCCESS:-1}" \
LIBERO_PRO_PAIRED_MIN_FAILED="${LIBERO_PRO_NATURAL_FAIL_MIN_FAILED:-1}" \
LIBERO_PRO_PAIRED_BASE_SEED="${LIBERO_PRO_NATURAL_FAIL_BASE_SEED:-195}" \
LIBERO_PRO_PAIRED_ROLLOUT_SEED_STEP="${LIBERO_PRO_NATURAL_FAIL_ROLLOUT_SEED_STEP:-97}" \
LIBERO_PRO_PAIRED_UNCERTAINTY_SEEDS="${LIBERO_PRO_NATURAL_FAIL_UNCERTAINTY_SEEDS:-0,1,2,3}" \
LIBERO_PRO_PAIRED_MAX_TIMESTEPS="${LIBERO_PRO_NATURAL_FAIL_MAX_TIMESTEPS:-220}" \
LIBERO_PRO_PAIRED_SAVE_VIDEOS="${LIBERO_PRO_NATURAL_FAIL_SAVE_VIDEOS:-0}" \
LIBERO_PRO_PAIRED_VIDEO_DIR="${LIBERO_PRO_NATURAL_FAIL_VIDEO_DIR:-../experiments/uncertainty/${LIBERO_PRO_NATURAL_FAIL_RUN_NAME:-natural_fail_mixed_grid}__videos}" \
"$SCRIPT_DIR/run_libero_pro_paired_prediction_collect.sh"
