#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

RUN_NAME="${LIBERO_PRO_CONTROLLED_FAIL_RUN_NAME:-controlled_fail_gripper_open_q3}"

LIBERO_PRO_PAIRED_RUN_NAME="$RUN_NAME" \
LIBERO_PRO_PAIRED_SUITES="${LIBERO_PRO_CONTROLLED_FAIL_SUITES:-libero_spatial_lan}" \
LIBERO_PRO_PAIRED_TASK_IDS="${LIBERO_PRO_CONTROLLED_FAIL_TASK_IDS:-0}" \
LIBERO_PRO_PAIRED_INIT_STATE_IDS="${LIBERO_PRO_CONTROLLED_FAIL_INIT_STATE_IDS:-0}" \
LIBERO_PRO_PAIRED_MAX_ROLLOUTS_PER_INIT="${LIBERO_PRO_CONTROLLED_FAIL_MAX_ROLLOUTS:-2}" \
LIBERO_PRO_PAIRED_MIN_SUCCESS="${LIBERO_PRO_CONTROLLED_FAIL_MIN_SUCCESS:-1}" \
LIBERO_PRO_PAIRED_MIN_FAILED="${LIBERO_PRO_CONTROLLED_FAIL_MIN_FAILED:-1}" \
LIBERO_PRO_PAIRED_BASE_SEED="${LIBERO_PRO_CONTROLLED_FAIL_BASE_SEED:-195}" \
LIBERO_PRO_PAIRED_ROLLOUT_SEED_STEP="${LIBERO_PRO_CONTROLLED_FAIL_ROLLOUT_SEED_STEP:-0}" \
LIBERO_PRO_PAIRED_UNCERTAINTY_SEEDS="${LIBERO_PRO_CONTROLLED_FAIL_UNCERTAINTY_SEEDS:-0,1,2,3}" \
LIBERO_PRO_PAIRED_MAX_TIMESTEPS="${LIBERO_PRO_CONTROLLED_FAIL_MAX_TIMESTEPS:-120}" \
LIBERO_PRO_PAIRED_SAVE_VIDEOS="${LIBERO_PRO_CONTROLLED_FAIL_SAVE_VIDEOS:-1}" \
LIBERO_PRO_PAIRED_VIDEO_DIR="${LIBERO_PRO_CONTROLLED_FAIL_VIDEO_DIR:-../experiments/uncertainty/${RUN_NAME}__videos}" \
LIBERO_PRO_PAIRED_INTERVENTION_MODE="${LIBERO_PRO_CONTROLLED_FAIL_INTERVENTION_MODE:-gripper}" \
LIBERO_PRO_PAIRED_INTERVENTION_START_T="${LIBERO_PRO_CONTROLLED_FAIL_INTERVENTION_START_T:-48}" \
LIBERO_PRO_PAIRED_INTERVENTION_END_T="${LIBERO_PRO_CONTROLLED_FAIL_INTERVENTION_END_T:-}" \
LIBERO_PRO_PAIRED_INTERVENTION_START_QUERY="${LIBERO_PRO_CONTROLLED_FAIL_INTERVENTION_START_QUERY:-}" \
LIBERO_PRO_PAIRED_INTERVENTION_END_QUERY="${LIBERO_PRO_CONTROLLED_FAIL_INTERVENTION_END_QUERY:-}" \
LIBERO_PRO_PAIRED_INTERVENTION_GRIPPER="${LIBERO_PRO_CONTROLLED_FAIL_INTERVENTION_GRIPPER:--1}" \
LIBERO_PRO_PAIRED_INTERVENTION_SCALE="${LIBERO_PRO_CONTROLLED_FAIL_INTERVENTION_SCALE:-}" \
LIBERO_PRO_PAIRED_INTERVENTION_BIAS="${LIBERO_PRO_CONTROLLED_FAIL_INTERVENTION_BIAS:-}" \
LIBERO_PRO_PAIRED_INTERVENTION_ROLLOUTS="${LIBERO_PRO_CONTROLLED_FAIL_INTERVENTION_ROLLOUTS:-1}" \
"$SCRIPT_DIR/run_libero_pro_paired_prediction_collect.sh"
