#!/usr/bin/env bash
set -euo pipefail

# Natural visual/background stressors: no action intervention.
# These suites keep the spatial instruction family but add different extra
# objects / tabletop layouts such as mug, red stick, and yellow book.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

LIBERO_PRO_PAIRED_RUN_NAME="${LIBERO_PRO_NATURAL_VISUAL_RUN_NAME:-natural_fail_visual_stressors}" \
LIBERO_PRO_PAIRED_SUITES="${LIBERO_PRO_NATURAL_VISUAL_SUITES:-libero_spatial_with_mug,libero_spatial_with_red_stick,libero_spatial_with_yellow_book}" \
LIBERO_PRO_PAIRED_TASK_IDS="${LIBERO_PRO_NATURAL_VISUAL_TASK_IDS:-0}" \
LIBERO_PRO_PAIRED_INIT_STATE_IDS="${LIBERO_PRO_NATURAL_VISUAL_INIT_STATE_IDS:-0}" \
LIBERO_PRO_PAIRED_MAX_ROLLOUTS_PER_INIT="${LIBERO_PRO_NATURAL_VISUAL_MAX_ROLLOUTS:-8}" \
LIBERO_PRO_PAIRED_MIN_SUCCESS="${LIBERO_PRO_NATURAL_VISUAL_MIN_SUCCESS:-1}" \
LIBERO_PRO_PAIRED_MIN_FAILED="${LIBERO_PRO_NATURAL_VISUAL_MIN_FAILED:-1}" \
LIBERO_PRO_PAIRED_BASE_SEED="${LIBERO_PRO_NATURAL_VISUAL_BASE_SEED:-195}" \
LIBERO_PRO_PAIRED_ROLLOUT_SEED_STEP="${LIBERO_PRO_NATURAL_VISUAL_ROLLOUT_SEED_STEP:-97}" \
LIBERO_PRO_PAIRED_UNCERTAINTY_SEEDS="${LIBERO_PRO_NATURAL_VISUAL_UNCERTAINTY_SEEDS:-0,1,2,3}" \
LIBERO_PRO_PAIRED_MAX_TIMESTEPS="${LIBERO_PRO_NATURAL_VISUAL_MAX_TIMESTEPS:-220}" \
LIBERO_PRO_PAIRED_SAVE_VIDEOS="${LIBERO_PRO_NATURAL_VISUAL_SAVE_VIDEOS:-0}" \
LIBERO_PRO_PAIRED_VIDEO_DIR="${LIBERO_PRO_NATURAL_VISUAL_VIDEO_DIR:-../experiments/uncertainty/${LIBERO_PRO_NATURAL_VISUAL_RUN_NAME:-natural_fail_visual_stressors}__videos}" \
"$SCRIPT_DIR/run_libero_pro_paired_prediction_collect.sh"
